# Generated by Django 5.1.7 on 2025-04-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_prompt_updated_by_historicalprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprompt',
            name='purpose',
            field=models.CharField(choices=[('deid', 'De-identification'), ('reid', 'Re-identification'), ('response', 'Actual prompt for responding the user question')], db_index=True, help_text='Purpose of the prompt', max_length=255),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='purpose',
            field=models.CharField(choices=[('deid', 'De-identification'), ('reid', 'Re-identification'), ('response', 'Actual prompt for responding the user question')], help_text='Purpose of the prompt', max_length=255, unique=True),
        ),
    ]
