# Generated by Django 5.1.7 on 2025-04-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_historicalprompt_purpose_alter_prompt_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprompt',
            name='model',
            field=models.CharField(choices=[('models/gemini-2.0-flash-lite', 'Gemini Flash 2.0 Lite')], help_text='AI/LLM model to be used for this purpose', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalprompt',
            name='prompt',
            field=models.TextField(help_text='The prompt to be used.'),
        ),
        migrations.AlterField(
            model_name='historicalprompt',
            name='purpose',
            field=models.CharField(choices=[('deid', 'De-identification'), ('reid', 'Re-identification'), ('response', 'The system prompt for the user question')], db_index=True, help_text='Purpose of the prompt', max_length=255),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='model',
            field=models.CharField(choices=[('models/gemini-2.0-flash-lite', 'Gemini Flash 2.0 Lite')], help_text='AI/LLM model to be used for this purpose', max_length=255),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt',
            field=models.TextField(help_text='The prompt to be used.'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='purpose',
            field=models.CharField(choices=[('deid', 'De-identification'), ('reid', 'Re-identification'), ('response', 'The system prompt for the user question')], help_text='Purpose of the prompt', max_length=255, unique=True),
        ),
    ]
